apps/fulfilment/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns("fulfilment.views",
    url(r"^packings/$",
        'packing_list',
        name='packing-list'),

    url (r"^packings/(?P<pk>[-\d]+)/$",
        'packing_detail',
        name='packing-detail'),   
    
    # Shipping    
    url(r"^shippings/$",
        'shipping_list',
        name='shipping-list'),
    url(
        r'^create/$',
        'create_packing_orders',
        name='create_packing_orders',
    ),    
)

apps/ordering/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(
        r'^sync/$',
        'ordering.views.ordering_sync_command',
        name='ordering_commands',
    ),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

from filebrowser.sites import site

urlpatterns = patterns("",
    url(r"^", include(admin.site.urls)),
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
)

# ShopifyPlus
urlpatterns += patterns("",
    url(r"^procurement/", include('procurement.urls')),
)

# ShopifyPlus
urlpatterns += patterns("",
    url(r"^shops/", include('shops.urls')),
    url(r"^fulfilment/", include('fulfilment.urls')),
    url(r"^invoices/", include('invoices.urls')),
    url(r"^products/", include('products.urls')),
    url(r"^ordering/", include('ordering.urls')),
)

if settings.SERVE_MEDIA:

    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += patterns('django.views.static',
        url(r'^site_media/media/(?P<path>.*)$',
            'serve',
            { 'document_root': settings.MEDIA_ROOT, },
        ),
    ) + staticfiles_urlpatterns()

apps/fulfilment/models.py
from django.db import models
from django.contrib.auth.models import User

from ordering.models import Order, OrderItem
from procurement.models import ProcurementItem
from products.models import ProductVariant


import datetime


class Packing(models.Model):
    """
    Based on Orders & ProcurementItem
    """
    order = models.ForeignKey(Order, unique=True)    

    @property
    def packing_order_cost(self):
        packing_items = PackingItem.objects.filter(packing=self)
        cost = 0
        for packing_item in packing_items:
            cost = cost + packing_item.packing_item_cost
        return cost

    def __unicode__(self):
        return u'%s' % self.order
    
class PackingItem(models.Model):
    """
    Corresponding to OrderItem
    and Procurement Item
    
    Packing values are calculated
    first from procurement items.
    
    Fulfilment values are defaulted
    to the packing values, yet are editable
    for adjustments.
    """
    
    packing = models.ForeignKey(
        Packing,
        editable=False)
    order_item = models.ForeignKey(
        OrderItem,
        editable=False)
    procurement_item = models.ForeignKey(
        ProcurementItem,
        editable=False)
    
    substitue_product_variant = models.ForeignKey(
        ProductVariant,
        blank=True,
        null=True)
    
    packing_weight = models.IntegerField(
        "p'weight",
        editable=False,
        blank=True,
        null=True)
    packing_quantity = models.IntegerField(
        "p'quantity",
        editable=False,
        blank=True,
        null=True)
    packing_unit_weight = models.IntegerField(
        "p'unit weight",
        editable=False,
        blank=True,
        null=True)
    packing_weight_price = models.FloatField(
        "p'weight price",
        editable=False,
        blank=True,
        null=True)
    packing_unit_price = models.FloatField(
        "p'unit price",
        editable=False,
        blank=True,
        null=True)
        
    fulfilment_weight = models.IntegerField(
        "f'weight",
        blank=True,
        null=True)
    fulfilment_quantity = models.IntegerField(
        "f'quantity",
        blank=True,
        null=True)
    fulfilment_unit_weight = models.IntegerField(
        "f'unit weight",
        blank=True,
        null=True)
    fulfilment_weight_price = models.FloatField(
        "f'weight price",
        blank=True,
        null=True)
    fulfilment_unit_price = models.FloatField(
        "f'unit price",
        blank=True,
        null=True)
        
    fulfilled = models.BooleanField()
    fulfilled_by = models.ForeignKey(
        User,
        blank=True,
        null=True)
    fulfilled_at = models.DateTimeField(
        blank=True,
        null=True)
    
    notes = models.TextField(
        blank=True,
        null=True)
        
    class Meta:
        unique_together = (
            'packing',
            'order_item',
            'procurement_item', )
        ordering = (
            'order_item__sku',)
        
    def __unicode__(self):
        return u'%s' % (self.order_item)

    @property
    def packing_item_cost(self):
        return self.packing_unit_price * self.packing_quantity
        
    @property
    def order_item_short_name(self):
        return self.order_item.short_name
        
    # def save(self):
    #     """ 
    #     Raise an Integrity Error or like if
    #     the order_item chosen does not belong
    #     to the Order related to via the PackingOrder
    #     """
    #     super.

apps/shopifyable/models/order.py
from django.db import models

from shopifyable.models import Shopifyable

class OrderItem(models.Model):

    shopify_product_id = models.PositiveIntegerField(
        blank=True,
        null=True)
    shopify_product_variant_id = models.PositiveIntegerField(
        blank=True,
        null=True)
    """
    Derive shopify_order_id from the parent order.
    """    
    shopify_order_id = models.PositiveIntegerField(
        blank=True,
        null=True)
    shopify_order_item_id = models.PositiveIntegerField(
        blank=True,
        null=True)
    fulfillment_service = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    fulfillment_status = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    grams = models.PositiveIntegerField(
        blank=True,
        null=True)
    name = models.TextField(
        blank=True,
        null=True)
    price = models.FloatField(
        blank=True,
        null=True)
    grams = models.PositiveIntegerField(
        blank=True,
        null=True)
    
    quantity = models.PositiveIntegerField()

    requires_shipping = models.BooleanField()
    
    sku = models.CharField(
        blank=True,
        max_length=255,
        null=True)
        
    title = models.CharField(
        blank=True,
        max_length=255,
        null=True)
        
    variant_title = models.CharField(
        blank=True,
        max_length=255,
        null=True)
        
    vendor = models.CharField(
        blank=True,
        max_length=255,
        null=True)
        
    class Meta: 
        abstract = True
        
    class Shopify:
        """
        Shopify field name on the left, and the corresponding
        Django ORM model field (on the right)
        """
        shopify_fields = {
            "fulfillment_service": "fulfillment_service",
            "fulfillment_status": "fulfillment_status",
            "grams": "grams",
            "id": "id",
            "name": "name", 
            "price": "price",
            "product_id": "shopify_product_id",
            "quantity": "quantity",
            "requires_shipping": "requires_shipping",
            "sku": "sku",
            "title": "title",
            "variant_id": "shopify_product_variant_id",
            "variant_title": "variant_title",
            "vendor": "vendor", }
        
    def __unicode__(self):
        return u'%s :: %s' % (self.title, self.variant_title)
        
class ShippingLine(models.Model):
    
    price = models.FloatField()
    code = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    title = models.CharField(
        blank=True,
        max_length=255,
        null=True)
        
    class Meta: 
        abstract = True
        
    class Shopify:
        shopify_fields = {
            "price": "price",
            "code": "code",
            "title": "title", }
        
    def __unicode__(self):
        return u'%s' % (self.title)
        
class OrderAddress(models.Model):

    name = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    first_name = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    last_name = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    address1 = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    address2 = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    city = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    company = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    zip = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    country_code = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    country = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    province = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    province_code = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    latitude = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    longitude = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
    phone = models.CharField(
        blank=True, 
        max_length=255,
        null=True)
        
    class Meta: 
        abstract = True
        
    class Shopify:
        shopify_fields = {
            "name": "name",
            "address1": "address1",
            "city": "city",
            "company": "company",
            "address2": "address2",
            "latitude": "latitude",
            "zip": "zip",
            "country_code": "country_code",
            "country": "country",
            "province_code": "province_code",
            "last_name": "last_name",
            "phone": "phone",
            "longitude": "longitude",
            "province": "province",
            "first_name": "first_name", }
            
    def __unicode__(self):
        return u'%s' % (self.address1)
            
class BillingAddress(OrderAddress):
    
    class Meta:
        abstract = True
        
    class Shopify:
        shopify_fields = OrderAddress.Shopify.shopify_fields
        
class ShippingAddress(OrderAddress):
    
    class Meta:
        abstract = True
        
    class Shopify:
        shopify_fields = OrderAddress.Shopify.shopify_fields
        
class DiscountCode(models.Model):
    
    code = models.CharField(
        blank=True,
        max_length=255)
   
    amount = models.FloatField(
        blank=True,
        null=True)
    
    class Meta:
        abstract = True
        
    class Shopify:
        shopify_fields = {
            "code": "code",
            "amount": "amount",
        }

    def __unicode__(self):
        return u'%s' % (self.code)

class TaxLine(models.Model):

    price = models.FloatField(
        blank=True,
        null=True)

    rate = models.FloatField(
        blank=True,
        null=True)

    title = models.CharField(
        blank=True,
        max_length=255)

    class Meta:
        abstract = True

    class Shopify:
        shopify_fields = {
            "price": "price",
            "rate": "rate",
            "title": "title",
        }

    def __unicode__(self):
        return u'%s' % (self.title)

class Order(Shopifyable):
    """
    An abstract model that Interfaces with its
    Shopify counterpart.
    """
    
    shopify_order_id = models.PositiveIntegerField(
        blank=True,
        null=True)
    browser_ip = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    buyer_accepts_marketing = models.BooleanField()
    closed_at = models.DateTimeField(
        blank=True,
        null=True)
    currency = models.CharField(
        blank=True,
        max_length=4,
        null=True)
    email = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    financial_status = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    fulfillment_status = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    gateway = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    landing_site = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    landing_site_ref = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    name = models.CharField(
        max_length=10)
    note = models.TextField(
        blank=True,
        null=True)
    note_attributes = models.TextField(
        blank=True,
        null=True)
    number = models.CharField(
        blank=True,
        max_length=10,
        null=True)
    order_number = models.CharField(
        blank=True,
        max_length=10,
        null=True)
    referring_site = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    subtotal_price = models.FloatField(
        blank=True,
        null=True)
    taxes_included = models.BooleanField()
    token = models.CharField(
        blank=True,
        max_length=255,
        null=True)
    total_discounts = models.FloatField(
        blank=True,
        null=True)
    total_line_items_price = models.FloatField(
        blank=True,
        null=True)
    total_price = models.FloatField(
        blank=True,
        null=True)
    total_weight = models.PositiveIntegerField(
        blank=True,
        null=True)
    total_tax = models.FloatField(
        blank=True,
        null=True)
    
    class Meta: 
        abstract = True
        
    class Shopify:
        shopify_fields = {
            'browser_ip': 'browser_ip',
            'buyer_accepts_marketing': 'buyer_accepts_marketing',
            'currency': 'currency',
            'email': 'email',
            'financial_status': 'financial_status',
            'fulfillment_status': 'fulfillment_status',
            'gateway': 'gateway',
            'id': 'shopify_order_id',
            'landing_site': 'landing_site',
            'landing_site_ref': 'landing_site_ref',
            'name': 'name',
            'note': 'note',
            'note_attributes': 'note_attributes',
            'number': 'number',
            'order_number': 'order_number',
            'referring_site': 'referring_site',
            'subtotal_price': 'subtotal_price',
            'taxes_included': 'taxes_included',
            'token': 'token',
            'total_discounts': 'total_discounts',
            'total_line_items_price': 'total_line_items_price',
            'total_price': 'total_price',
            'total_tax': 'total_tax',
            'total_weight': 'total_weight', }
        shopify_date_fields = {
            'closed_at': 'closed_at',
            'created_at': 'created_at',

apps/fulfilment/views.py
from django.views import generic
from django.core import management
from django.views.generic.detail import SingleObjectMixin
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.http import HttpResponseRedirect

from shops.models import Shop
from invoices.models import Invoice, InvoiceItem
from fulfilment.models import Packing, PackingItem
from procurement.models import Procurement

from fulfilment.utils import packing_item_defaults, process_procurement_orders


class PackingMixin(object):
    model = Packing
    paginate_by = 250

    def get_queryset(self):
        return super(PackingMixin, self).get_queryset().select_related().filter()

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        return queryset.get()


class PackingList(PackingMixin, generic.ListView):
    pass
packing_list = PackingList.as_view()


class ShippingList(PackingMixin, generic.ListView):
    template_name = "fulfilment/shipping_list.html"
shipping_list = ShippingList.as_view()


# class PackingDetail(PackingMixin, generic.DetailView):
#     pass
# packing_detail = PackingDetail.as_view()

class PackingDetailView(generic.DetailView):

    model = Packing

    def render(self, context):
        context['packing'] = object

packing_detail = PackingDetailView.as_view()



def create_packing_orders(request):
    """
    Generates packing from procurements
    """

    shop = Shop.objects.get()

    # Delete previous packing/invoices
    # TODO: Keep them! But make sure they get closed
    management.call_command('reset', 'fulfilment', noinput=True, verbosity=0, interactive=False);
    management.call_command('reset', 'invoices', noinput=True, verbosity=0, interactive=False);

    # Create packing
    # TODO: Select the shop only
    print "Creating packing..."
    procurements = Procurement.objects.all()
    packings = process_procurement_orders(procurements)

    # Set packing item defaults
    print "Setting item defaults..."
    items = PackingItem.objects.filter(packing__in=packings)
    packing_item_defaults(items)

    return HttpResponseRedirect('/')

templates/fulfilment/includes/_packing_item.html
{% load custom_filters %}

        <article class="packing page-break-after">
            <aside class="span6">
                <dl>
                    {% if packing.order.customer.note %}
                    <dt>Customer note:</dt>
                    <dd>{{ packing.order.customer.note }}</dd>
                    {% endif %}

                    {% if packing.order.note %}
                    <dt>Order note:</dt>
                    <dd>{{ packing.order.note }}</dd>
                    {% endif %}

                    {% if packing.order.customer.shipping_notes %}
                    <dt>Customer Shipping notes:</dt>
                    <dd>{{ packing.order.customer.shipping_notes }}</dd>
                    {% endif %}

                    {% if packing.order.note_attributes|length > 5 %}
                    <dt>Customer Shipping notes:</dt>
                    <dd class="json">{{ packing.order.note_attributes }}</dd>
                    {% endif %}
                </dl>

                <table cellspacing="0" cellpadding="0" class="totals">
                    {% if packing.order.discountcode_set.all %}
                    <tr>
                        <th valign="top">Discounts:</th>
                        <td>
                            {% for discount_code in packing.order.discountcode_set.all %}
                                <span style="font-size: 12px;">({{ discount_code.code }}): {{ discount_code.amount|currency_filter:1 }}</span><br/>
                            {% endfor %}
                            <hr/>
                            <span style="font-size: 12px; font-weight:bold;">Total: {{ packing.order.total_discounts|currency_filter:1 }}</span>
                        </td>
                    </tr>
                    {% endif %}

                    <tr>
                        <th>Subtotal:</th><td>{{ packing.order.subtotal_price|currency_filter:1|default:"&nbsp;" }}</td>
                    </tr>
                    <tr>
                        <th valign="top">Shipping:</th>
                        <td>
                            {% for shipping_line in packing.order.shippingline_set.all %}
                                <span style="font-size: 12px;">({{ shipping_line.title }}): {{ shipping_line.price|currency_filter:1 }}</span><br/>
                            {% endfor %}
                        </td>
                    </tr>

                    {% for tax_line in packing.order.taxline_set.all %}

                        <tr>
                            <th>{{ tax_line.title }}:</th><td>{{ tax_line.price|currency_filter:1 }}</td>
                        </tr>

                    {% endfor %}

                    <tr class="total-border">
                        <th>Total:</th><td><strong>{{ packing.order.total_price|currency_filter:1 }}</strong></td>
                    </tr>

                </table>
            </aside>

            <table class="check-list span6 pull-right" cellpadding="2px">
                <tr>
                    <td>Packed by</td>
                    <td>____________</td>
                </tr>
                <tr>
                    <td>Notes done &amp; ticked</td>
                    <td>____________</td>
                </tr>
                <tr>
                    <td>No. products missing</td>
                    <td>____________</td>
                </tr>
                <tr>
                    <td>No. of bonuses included</td>
                    <td>____________</td>
                </tr>
                <tr>
                    <td>Order checked by</td>
                    <td>____________</td>
                </tr>
                <tr>
                    <td>Card added OO/NC/R/M</td>
                    <td>____________</td>
                </tr>
                <tr>
                    <td>New Label on box</td>
                    <td>____________</td>
                </tr>
                <tr>
                    <td>Boxes Numbered</td>
                    <td>____________</td>
                </tr>
            </table>

            <div class="clearfix"></div><br />

            <table cellspacing="0" cellpadding="0" class="table table-striped table-bordered table-condensed" >

                <tr>
                    <thead>
                        <td class="quantity" width="5%">&#10004;</td>
                        <td width="30%">Item</td>
                        <td class="quantity" width="5%">Qty</td>
                        <td class="quantity" width="5%">&#10004;</td>
                        <td class="rightalign" width="10%">Order weight</td>
                        <td class="rightalign" width="10%">$ per kg</td>
                        <td class="rightalign" width="10%">U Price</td>
                        <td class="rightalign" width="35%">Order Cost</td>
                    </thead>
                </tr>

            {% for packing_item in packing.packingitem_set.all %}

                <tr>
                    <td class="check-list-box">&nbsp;</td>
                    <td>
                        {% comment %} If there is a variant short title, use that  {% endcomment %}
                        {% if packing_item.order_item.variant_short_title %}
                            {{ packing_item.order_item.variant_short_title|default:"&nbsp;" }}
                        {% else %}
                            {{ packing_item.order_item.short_name|default:"&nbsp;" }}
                        {% endif %}
                        <small>{{ packing_item.order_item.sku|default:"&nbsp;" }}</small>
                    </td>
                    <td class="quantity">{{ packing_item.packing_quantity|default:"&nbsp;" }}</td>
                    <td class="check-list-box">&nbsp;</td>
                    <td class="rightalign">{{ packing_item.packing_weight|default:"&nbsp;" }}</td>
                    <td class="rightalign">{{ packing_item.packing_weight_price|currency_filter:1|default:"&nbsp;" }}</td>
                    <td class="rightalign">{{ packing_item.packing_unit_price|currency_filter:1|default:"&nbsp;" }}</td>
                    <td class="rightalign">{{ packing_item.packing_item_cost|currency_filter:1|default:"&nbsp;" }}</td>
                </tr>

            {% endfor %}

            </table>

            {% comment %}
            <table cellspacing="0" cellpadding="0" class="totals page-break-after">
                <tr>
                    <th><b>Total:</b></th><td>{{ packing.packing_order_cost|currency_filter:1 }}</td>
                </tr>
            </table>
            {% endcomment %}
        </article>